### ISSUE TITLE
Security vulnerability detected for axios

### ISSUE THREAD

**Issue by einsiol** [ramasilveyra/stylelint-images#12]
There is a *Moderate* vulnerability warning being caused by an outdated dependency in this project.

This is what I get when I run `npm audit` on my project that has `stylelint-images` as a dependency.

| **Moderate**   |      **Denial of Service **      | 
|----------|:-------------:|
| Package | axios  |
| Patched in |  >=0.18.1  |
| Dependency of  |   stylelint-images [dev]     |
| Path  | stylelint-images > axios | 
| More info   | https://npmjs.com/advisories/880   | 

This issue cannot be fixed automatically with `npm audit fix` and has to be fixed here. Is it possible to update this package here?

**Comment by ramasilveyra** [comment]
Thanks! Sorry for the delay. Fix merged, released under v2.0.1. Have a great year!
