### ISSUE TITLE
Update to support newer version of Stylelint

### ISSUE THREAD

**Issue by deiga** [ramasilveyra/stylelint-images#8]

**Comment by ramasilveyra** [comment]
Fixed with #9 . I will ping you as soon as I made the release

**Comment by pkuczynski** [comment]
Awesome, thanks! Any chance for a release soon?

**Comment by ramasilveyra** [comment]
@pkuczynski @deiga It was released on v2.0.0: https://github.com/ramasilveyra/stylelint-images/blob/master/CHANGELOG.md#200-2018-02-25

**Comment by pkuczynski** [comment]
Cool!
